import "./globals.css";
import type { Metadata } from "next";
import { LocaleContextProvider } from "@/context/locale.context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <div className="max-w-sm w-full mx-auto bg-white min-h-screen relative">
          <LocaleContextProvider>{children}</LocaleContextProvider>
        </div>
      </body>
    </html>
  );
}
